/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBuyersRouteImport } from './routes/admin.buyers'
import { Route as AdminDiscountsRouteImport } from './routes/admin.discounts'
import { Route as AdminErpRouteImport } from './routes/admin.erp'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminNearExpiryRouteImport } from './routes/admin.near-expiry'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as BuyerIndexRouteImport } from './routes/buyer.index'
import { Route as BuyerAccountRouteImport } from './routes/buyer.account'
import { Route as BuyerCartRouteImport } from './routes/buyer.cart'
import { Route as BuyerCheckoutRouteImport } from './routes/buyer.checkout'
import { Route as BuyerOffersRouteImport } from './routes/buyer.offers'
import { Route as DispatchIndexRouteImport } from './routes/dispatch.index'
import { Route as DispatchInTransitRouteImport } from './routes/dispatch.in-transit'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as FinanceCodRouteImport } from './routes/finance.cod'
import { Route as FinanceCreditRouteImport } from './routes/finance.credit'
import { Route as FinancePaymentsRouteImport } from './routes/finance.payments'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as WarehouseIndexRouteImport } from './routes/warehouse.index'
import { Route as WarehouseIdRouteImport } from './routes/warehouse.$id'
import { Route as WarehouseInventoryRouteImport } from './routes/warehouse.inventory'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as BuyerOrdersIndexRouteImport } from './routes/buyer.orders.index'
import { Route as BuyerOrdersIdRouteImport } from './routes/buyer.orders.$id'
import { Route as AdminOrdersIdInvoiceRouteImport } from './routes/admin.orders.$id_.invoice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuyersRoute = AdminBuyersRouteImport.update({
  id: '/admin/buyers',
  path: '/admin/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/admin/discounts',
  path: '/admin/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminErpRoute = AdminErpRouteImport.update({
  id: '/admin/erp',
  path: '/admin/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNearExpiryRoute = AdminNearExpiryRouteImport.update({
  id: '/admin/near-expiry',
  path: '/admin/near-expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/buyer/',
  path: '/buyer/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerAccountRoute = BuyerAccountRouteImport.update({
  id: '/buyer/account',
  path: '/buyer/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerCartRoute = BuyerCartRouteImport.update({
  id: '/buyer/cart',
  path: '/buyer/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerCheckoutRoute = BuyerCheckoutRouteImport.update({
  id: '/buyer/checkout',
  path: '/buyer/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerOffersRoute = BuyerOffersRouteImport.update({
  id: '/buyer/offers',
  path: '/buyer/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchIndexRoute = DispatchIndexRouteImport.update({
  id: '/dispatch/',
  path: '/dispatch/',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchInTransitRoute = DispatchInTransitRouteImport.update({
  id: '/dispatch/in-transit',
  path: '/dispatch/in-transit',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCodRoute = FinanceCodRouteImport.update({
  id: '/finance/cod',
  path: '/finance/cod',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCreditRoute = FinanceCreditRouteImport.update({
  id: '/finance/credit',
  path: '/finance/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/finance/reports',
  path: '/finance/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseIndexRoute = WarehouseIndexRouteImport.update({
  id: '/warehouse/',
  path: '/warehouse/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseIdRoute = WarehouseIdRouteImport.update({
  id: '/warehouse/$id',
  path: '/warehouse/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseInventoryRoute = WarehouseInventoryRouteImport.update({
  id: '/warehouse/inventory',
  path: '/warehouse/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/admin/orders/$id',
  path: '/admin/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerOrdersIndexRoute = BuyerOrdersIndexRouteImport.update({
  id: '/buyer/orders/',
  path: '/buyer/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerOrdersIdRoute = BuyerOrdersIdRouteImport.update({
  id: '/buyer/orders/$id',
  path: '/buyer/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdInvoiceRoute = AdminOrdersIdInvoiceRouteImport.update({
  id: '/admin/orders/$id_/invoice',
  path: '/admin/orders/$id/invoice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/erp': typeof AdminErpRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/near-expiry': typeof AdminNearExpiryRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/offers': typeof BuyerOffersRoute
  '/dispatch/in-transit': typeof DispatchInTransitRoute
  '/finance/cod': typeof FinanceCodRoute
  '/finance/credit': typeof FinanceCreditRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/warehouse/$id': typeof WarehouseIdRoute
  '/warehouse/inventory': typeof WarehouseInventoryRoute
  '/admin/': typeof AdminIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/dispatch/': typeof DispatchIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/warehouse/': typeof WarehouseIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/buyer/orders/$id': typeof BuyerOrdersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/buyer/orders/': typeof BuyerOrdersIndexRoute
  '/admin/orders/$id/invoice': typeof AdminOrdersIdInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/erp': typeof AdminErpRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/near-expiry': typeof AdminNearExpiryRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/offers': typeof BuyerOffersRoute
  '/dispatch/in-transit': typeof DispatchInTransitRoute
  '/finance/cod': typeof FinanceCodRoute
  '/finance/credit': typeof FinanceCreditRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/warehouse/$id': typeof WarehouseIdRoute
  '/warehouse/inventory': typeof WarehouseInventoryRoute
  '/admin': typeof AdminIndexRoute
  '/buyer': typeof BuyerIndexRoute
  '/dispatch': typeof DispatchIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/warehouse': typeof WarehouseIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/buyer/orders/$id': typeof BuyerOrdersIdRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/buyer/orders': typeof BuyerOrdersIndexRoute
  '/admin/orders/$id/invoice': typeof AdminOrdersIdInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/erp': typeof AdminErpRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/near-expiry': typeof AdminNearExpiryRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/offers': typeof BuyerOffersRoute
  '/dispatch/in-transit': typeof DispatchInTransitRoute
  '/finance/cod': typeof FinanceCodRoute
  '/finance/credit': typeof FinanceCreditRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/warehouse/$id': typeof WarehouseIdRoute
  '/warehouse/inventory': typeof WarehouseInventoryRoute
  '/admin/': typeof AdminIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/dispatch/': typeof DispatchIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/warehouse/': typeof WarehouseIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/buyer/orders/$id': typeof BuyerOrdersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/buyer/orders/': typeof BuyerOrdersIndexRoute
  '/admin/orders/$id_/invoice': typeof AdminOrdersIdInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/audit'
    | '/admin/buyers'
    | '/admin/discounts'
    | '/admin/erp'
    | '/admin/inventory'
    | '/admin/near-expiry'
    | '/admin/permissions'
    | '/admin/reports'
    | '/buyer/account'
    | '/buyer/cart'
    | '/buyer/checkout'
    | '/buyer/offers'
    | '/dispatch/in-transit'
    | '/finance/cod'
    | '/finance/credit'
    | '/finance/payments'
    | '/finance/reports'
    | '/warehouse/$id'
    | '/warehouse/inventory'
    | '/admin/'
    | '/buyer/'
    | '/dispatch/'
    | '/finance/'
    | '/warehouse/'
    | '/admin/orders/$id'
    | '/buyer/orders/$id'
    | '/admin/orders/'
    | '/buyer/orders/'
    | '/admin/orders/$id/invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/audit'
    | '/admin/buyers'
    | '/admin/discounts'
    | '/admin/erp'
    | '/admin/inventory'
    | '/admin/near-expiry'
    | '/admin/permissions'
    | '/admin/reports'
    | '/buyer/account'
    | '/buyer/cart'
    | '/buyer/checkout'
    | '/buyer/offers'
    | '/dispatch/in-transit'
    | '/finance/cod'
    | '/finance/credit'
    | '/finance/payments'
    | '/finance/reports'
    | '/warehouse/$id'
    | '/warehouse/inventory'
    | '/admin'
    | '/buyer'
    | '/dispatch'
    | '/finance'
    | '/warehouse'
    | '/admin/orders/$id'
    | '/buyer/orders/$id'
    | '/admin/orders'
    | '/buyer/orders'
    | '/admin/orders/$id/invoice'
  id:
    | '__root__'
    | '/'
    | '/admin/audit'
    | '/admin/buyers'
    | '/admin/discounts'
    | '/admin/erp'
    | '/admin/inventory'
    | '/admin/near-expiry'
    | '/admin/permissions'
    | '/admin/reports'
    | '/buyer/account'
    | '/buyer/cart'
    | '/buyer/checkout'
    | '/buyer/offers'
    | '/dispatch/in-transit'
    | '/finance/cod'
    | '/finance/credit'
    | '/finance/payments'
    | '/finance/reports'
    | '/warehouse/$id'
    | '/warehouse/inventory'
    | '/admin/'
    | '/buyer/'
    | '/dispatch/'
    | '/finance/'
    | '/warehouse/'
    | '/admin/orders/$id'
    | '/buyer/orders/$id'
    | '/admin/orders/'
    | '/buyer/orders/'
    | '/admin/orders/$id_/invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBuyersRoute: typeof AdminBuyersRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminErpRoute: typeof AdminErpRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminNearExpiryRoute: typeof AdminNearExpiryRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  BuyerAccountRoute: typeof BuyerAccountRoute
  BuyerCartRoute: typeof BuyerCartRoute
  BuyerCheckoutRoute: typeof BuyerCheckoutRoute
  BuyerOffersRoute: typeof BuyerOffersRoute
  DispatchInTransitRoute: typeof DispatchInTransitRoute
  FinanceCodRoute: typeof FinanceCodRoute
  FinanceCreditRoute: typeof FinanceCreditRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  WarehouseIdRoute: typeof WarehouseIdRoute
  WarehouseInventoryRoute: typeof WarehouseInventoryRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
  DispatchIndexRoute: typeof DispatchIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  WarehouseIndexRoute: typeof WarehouseIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  BuyerOrdersIdRoute: typeof BuyerOrdersIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  BuyerOrdersIndexRoute: typeof BuyerOrdersIndexRoute
  AdminOrdersIdInvoiceRoute: typeof AdminOrdersIdInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/buyers': {
      id: '/admin/buyers'
      path: '/admin/buyers'
      fullPath: '/admin/buyers'
      preLoaderRoute: typeof AdminBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/admin/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/erp': {
      id: '/admin/erp'
      path: '/admin/erp'
      fullPath: '/admin/erp'
      preLoaderRoute: typeof AdminErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/near-expiry': {
      id: '/admin/near-expiry'
      path: '/admin/near-expiry'
      fullPath: '/admin/near-expiry'
      preLoaderRoute: typeof AdminNearExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/buyer'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/account': {
      id: '/buyer/account'
      path: '/buyer/account'
      fullPath: '/buyer/account'
      preLoaderRoute: typeof BuyerAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/cart': {
      id: '/buyer/cart'
      path: '/buyer/cart'
      fullPath: '/buyer/cart'
      preLoaderRoute: typeof BuyerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/checkout': {
      id: '/buyer/checkout'
      path: '/buyer/checkout'
      fullPath: '/buyer/checkout'
      preLoaderRoute: typeof BuyerCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/offers': {
      id: '/buyer/offers'
      path: '/buyer/offers'
      fullPath: '/buyer/offers'
      preLoaderRoute: typeof BuyerOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/': {
      id: '/dispatch/'
      path: '/dispatch'
      fullPath: '/dispatch/'
      preLoaderRoute: typeof DispatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/in-transit': {
      id: '/dispatch/in-transit'
      path: '/dispatch/in-transit'
      fullPath: '/dispatch/in-transit'
      preLoaderRoute: typeof DispatchInTransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/cod': {
      id: '/finance/cod'
      path: '/finance/cod'
      fullPath: '/finance/cod'
      preLoaderRoute: typeof FinanceCodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/credit': {
      id: '/finance/credit'
      path: '/finance/credit'
      fullPath: '/finance/credit'
      preLoaderRoute: typeof FinanceCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/finance/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/': {
      id: '/warehouse/'
      path: '/warehouse'
      fullPath: '/warehouse/'
      preLoaderRoute: typeof WarehouseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/$id': {
      id: '/warehouse/$id'
      path: '/warehouse/$id'
      fullPath: '/warehouse/$id'
      preLoaderRoute: typeof WarehouseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/inventory': {
      id: '/warehouse/inventory'
      path: '/warehouse/inventory'
      fullPath: '/warehouse/inventory'
      preLoaderRoute: typeof WarehouseInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/orders/': {
      id: '/buyer/orders/'
      path: '/buyer/orders'
      fullPath: '/buyer/orders/'
      preLoaderRoute: typeof BuyerOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/orders/$id': {
      id: '/buyer/orders/$id'
      path: '/buyer/orders/$id'
      fullPath: '/buyer/orders/$id'
      preLoaderRoute: typeof BuyerOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id_/invoice': {
      id: '/admin/orders/$id_/invoice'
      path: '/admin/orders/$id/invoice'
      fullPath: '/admin/orders/$id/invoice'
      preLoaderRoute: typeof AdminOrdersIdInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBuyersRoute: AdminBuyersRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminErpRoute: AdminErpRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminNearExpiryRoute: AdminNearExpiryRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  BuyerAccountRoute: BuyerAccountRoute,
  BuyerCartRoute: BuyerCartRoute,
  BuyerCheckoutRoute: BuyerCheckoutRoute,
  BuyerOffersRoute: BuyerOffersRoute,
  DispatchInTransitRoute: DispatchInTransitRoute,
  FinanceCodRoute: FinanceCodRoute,
  FinanceCreditRoute: FinanceCreditRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  WarehouseIdRoute: WarehouseIdRoute,
  WarehouseInventoryRoute: WarehouseInventoryRoute,
  AdminIndexRoute: AdminIndexRoute,
  BuyerIndexRoute: BuyerIndexRoute,
  DispatchIndexRoute: DispatchIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  WarehouseIndexRoute: WarehouseIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  BuyerOrdersIdRoute: BuyerOrdersIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  BuyerOrdersIndexRoute: BuyerOrdersIndexRoute,
  AdminOrdersIdInvoiceRoute: AdminOrdersIdInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
